import time
timestamp =time.strftime('%I:%M:%S %p')
print(timestamp)
timestamp=time.strftime('%I')
print(timestamp)
timestamp=time.strftime('%M')
print(timestamp)
timestamp=time.strftime('%S')
print(timestamp)
timestamp=time.strftime('%p')
print(timestamp)